spring:
  application:
    name: portotemp-api

  datasource:
    url: jdbc:postgresql://localhost:5432/portotemp
    username: portotemp_user
    password: portotemp_senha_segura_2026
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

jwt:
  secret: dev_secret_local_apenas_deve_ter_no_minimo_32_chars
  expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG
