services:
  portotemp_postgres_dev:
    image: postgres:16-alpine
    container_name: portotemp_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: portotemp
      POSTGRES_USER: portotemp_user
      POSTGRES_PASSWORD: portotemp_senha_segura_2026
    ports:
      - "5432:5432"
    volumes:
      - portotemp_postgres_dev_data:/var/lib/postgresql/data

volumes:
  portotemp_postgres_dev_data:
